#define COMBO_ALLOW_ACTION_KEYS
#define COMBO_VARIABLE_LEN

#undef TAPPING_TERM
#define TAPPING_TERM 140
#define TAPPING_TERM_PER_KEY

#define PERMISSIVE_HOLD

#define IGNORE_MOD_TAP_INTERRUPT

#define BILATERAL_COMBINATIONS
